### ISSUE TITLE
Deprecated APIs blocking merge

### ISSUE THREAD

**Issue by mrhappyasthma** [mrhappyasthma/runelite-profit-tracker#19]
net.runelite.pluginhub.packager.PluginBuildException: profit-tracker: plugin uses terminally deprecated APIs:
Use ComponentID or InterfaceID instead of WidgetInfo or WidgetID
	at net.runelite.pluginhub.packager.PluginBuildException.of(PluginBuildException.java:54)
	at net.runelite.pluginhub.packager.Plugin.assembleDisplayData(Plugin.java:764)
	at net.runelite.pluginhub.packager.Plugin.build(Plugin.java:550)
	at net.runelite.pluginhub.packager.Packager.buildPlugin(Packager.java:215)
	at net.runelite.pluginhub.packager.Packager.lambda$buildPlugins$0(Packager.java:155)
	at java.base/java.lang.Thread.run(Thread.java:829)

profit-tracker: plugin uses terminally deprecated APIs:
Use ComponentID or InterfaceID instead of WidgetInfo or WidgetID

**Comment by mrhappyasthma** [comment]
It's used in this line:

**Comment by mrhappyasthma** [comment]
idk what hotkey i hit but I accentally closed it instead of pasting. we only use those on this line:

`xpDropWidget = client.getWidget(TO_GROUP(xpDropWidgetId), TO_CHILD(xpDropWidgetId));`

**Comment by mrhappyasthma** [comment]
Looks like there's a new widget ID paradigm:
https://github.com/runelite/runelite/commit/00a78d9a4903782c0041dbb71ca49f80274d09e0#diff-9a37a00a5fdffe06ae8c8515fb71e9ec02b19f772c238fb2670cea0ee49e0ba2L33

Seems like the upper 16 bits are used for the childId and the lower 16 bits are used for the groupId now.

**Comment by mrhappyasthma** [comment]
This is still erroring for some reason:

```
net.runelite.pluginhub.packager.PluginBuildException: profit-tracker: plugin uses terminally deprecated APIs:
Use ComponentID or InterfaceID instead of WidgetInfo or WidgetID
	at net.runelite.pluginhub.packager.PluginBuildException.of(PluginBuildException.java:54)
	at net.runelite.pluginhub.packager.Plugin.assembleDisplayData(Plugin.java:764)
	at net.runelite.pluginhub.packager.Plugin.build(Plugin.java:550)
	at net.runelite.pluginhub.packager.Packager.buildPlugin(Packager.java:215)
	at net.runelite.pluginhub.packager.Packager.lambda$buildPlugins$0(Packager.java:155)
	at java.base/java.lang.Thread.run(Thread.java:[82](https://github.com/runelite/plugin-hub/actions/runs/12847263388/job/35823366711?pr=7250#step:6:83)9)
```

**Comment by mrhappyasthma** [comment]
Oh we still have `WidgetID` here: https://github.com/mrhappyasthma/runelite-profit-tracker/blob/5905c060f655a79db6e15198eddd53d6032b0282/src/main/java/com/profittracker/ProfitTrackerPlugin.java#L10

**Comment by mrhappyasthma** [comment]
It's used for seed vault: https://github.com/mrhappyasthma/runelite-profit-tracker/blob/5905c060f655a79db6e15198eddd53d6032b0282/src/main/java/com/profittracker/ProfitTrackerPlugin.java#L228

**Comment by mrhappyasthma** [comment]
We should be able to replace with `InterfaceID.SEED_VAULT`

**Comment by mrhappyasthma** [comment]
Thanks for the help fixing these up. Checks are passing now, just waiting on them to approve and merge it: https://github.com/runelite/plugin-hub/pull/7253
